apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mariadb-pvc
  #namespace: student-namespace
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
